version: '3.9'

services:
  mongo:
    container_name: mongo_chatio
    image: mongo:4.4.10-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: chat.io